disable haddock & sdist until later

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -28,13 +28,13 @@ script:
  - cabal install -v2 --enable-tests --enable-benchmarks --program-suffix=-$(cabal info .|head -n 1|cut -d' ' -f2|cut -d'-' -f2)-$(git log HEAD~1..HEAD --pretty=%h)
  - cabal test
  - cabal check
- - cabal haddock
- - cabal sdist
- - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
-   cd dist/;
-   if [ -f "$SRC_TGZ" ]; then
-      cabal install --force-reinstalls "$SRC_TGZ";
-   else
-      echo "expected '$SRC_TGZ' not found";
-      exit 1;
-   fi
+ # - cabal haddock
+ # - cabal sdist
+ # - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+ #   cd dist/;
+ #   if [ -f "$SRC_TGZ" ]; then
+ #      cabal install --force-reinstalls "$SRC_TGZ";
+ #   else
+ #      echo "expected '$SRC_TGZ' not found";
+ #      exit 1;
+ #   fi
