update travisci build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,19 +19,19 @@ install:
  - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/core
  - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/amazonka
  - cabal sandbox add-source ./.cabal-sandbox/src/amazonka/amazonka-ec2
- - cabal install --enable-tests --enable-benchmarks --only-dependencies
+ - cabal install --only-dependencies
 
 script:
  - cabal check
- - cabal install -v2 --enable-tests --enable-benchmarks --program-suffix=-$(cabal info .|head -n 1|cut -d' ' -f2|cut -d'-' -f2)-$(git log HEAD~1..HEAD --pretty=%h)
+ - cabal install -v2 --program-suffix=-$(cabal info .|head -n 1|cut -d' ' -f2|cut -d'-' -f2)
  - cabal test
- # - cabal haddock
- # - cabal sdist
- # - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
- #   cd dist/;
- #   if [ -f "$SRC_TGZ" ]; then
- #      cabal install --force-reinstalls "$SRC_TGZ";
- #   else
- #      echo "expected '$SRC_TGZ' not found";
- #      exit 1;
- #   fi
+#- cabal haddock
+ - cabal sdist
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
